<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_detail_name</name>
   <tag></tag>
   <elementGuidId>65da460c-6ebc-43ce-b108-cad929aba104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[@class='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[@class='name']</value>
      <webElementGuid>4b234f53-3196-4181-82b7-d574d47e1bbc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
