<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_form_login</name>
   <tag></tag>
   <elementGuidId>eff06159-190c-40c3-bbb1-ae5d2d9c2415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id=&quot;login2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id=&quot;login2&quot;]</value>
      <webElementGuid>fb573885-dff2-4d83-a6f4-a7a8955b58f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
