<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cart_page</name>
   <tag></tag>
   <elementGuidId>a8ff9881-87e0-471c-9ae3-264b5cca0549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id=&quot;cartur&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id=&quot;cartur&quot;]</value>
      <webElementGuid>a77e04e9-77d4-454d-9380-01036690a2e6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
