<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_name_clickable</name>
   <tag></tag>
   <elementGuidId>042b7fe8-d94c-4440-87c0-b9556274612d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h4/a[normalize-space(.)=&quot;${productName}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h4/a[normalize-space(.)=&quot;${productName}&quot;]</value>
      <webElementGuid>aa36a85b-b09b-4a73-bc87-30614c6bff3f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
