<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_purcase</name>
   <tag></tag>
   <elementGuidId>ef160549-31c5-49c7-ba75-e946275aec66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[text()='Purchase']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[text()='Purchase']</value>
      <webElementGuid>57c8c8fd-eb14-4e87-8f51-a236e16e97c6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
