<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkout</name>
   <tag></tag>
   <elementGuidId>d42a4362-2208-48ee-a91c-026f64985830</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;${inputId}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;${inputId}&quot;]</value>
      <webElementGuid>623c4b42-d4e9-4637-a107-b441737bdb3b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
