<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_login</name>
   <tag></tag>
   <elementGuidId>947e5e7e-30cd-4c51-92d5-deddf8cb7e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;${field}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;${field}&quot;]</value>
      <webElementGuid>873e0b8e-b21b-465f-8aac-c325a36f6b87</webElementGuid>
   </webElementProperties>
</WebElementEntity>
